### ISSUE TITLE
There should be a Simple container that can conain only 1 drop-in

### ISSUE THREAD

**Issue by NicolasAnquetil** [pharo-contributions/durden#1]
Currently the base container is SpDropInContainer that can accept an unlimited number of drop-ins.
Each time a drop-in is added, a new empty spot is created to accept one more

When using SpDropInPanedContainer, this is very strange a the pane can contain two lists of drop-in.

The current behaviour of SpDropInContainer should be put in a SpDropInUnlimitedContainer and SpDropInContainer can contain only one drop-in.
Then SpDropInUnlimitedContainer can use SpDropInContainer and create new ones

**Comment by sbragagnolo** [comment]
Now i splitted the hierarchy into single and multiple to cover this case and the other case :) .
